#48 - Adding a way to allow bg color change without affecting the cur…
yashchaudhari008/drawit pull request #54
Opened 2021-10-29 19:47 UTC by brunojuliao

After some investigation, I noticed the background actually is applied as a fill operation, which wouldn't allow us to replace it easily. So, I left canvas as transparent and changed the action to only affect the canva HTML element background color. Then, on save, store the current state, then blends the background and the content to save and restore the state to continue working.
:)

2021-10-30 04:43 UTC, yashchaudhari008 requested changes
Issue:- As currently eraser is using background colour as stroke color if we eraser something then change background- strokes or eraser are visible too! 

Reference:-
![image](https://user-images.githubusercontent.com/29065088/139520465-5fe7e7ce-d828-48f3-84ba-01cdbdf8e494.png)

2021-10-30 10:12 UTC, brunojuliao commented
Oh, I see... I'm sorry for missing this.
I won't be able to work on this today. I'll fix it tomorrow or the day after as I'll need some time to figure out a fix for this 😇

2021-11-01 21:13 UTC, brunojuliao commented
Added a commit to fix the eraser. Please, note the eraser won't affect the background, in the sense that background can't be erased.

2021-11-02 14:16 UTC, yashchaudhari008 approved these changes

2021-11-02 14:19 UTC, brunojuliao commented
I'll give it a try 😇

2021-11-02 14:39 UTC, brunojuliao commented on AppData/index.js
> +function saveCanvasInternal(fileName) {
I'll give it a try 😇

2021-11-02 15:06 UTC, brunojuliao commented on AppData/index.js
> +function saveCanvasInternal(fileName) {
Did some refactor ;)

2021-11-03 06:22 UTC, yashchaudhari008 commented
After saving , drawing and then changing background causes this!
![image](https://user-images.githubusercontent.com/29065088/140016986-2f25a974-c5aa-4c53-9105-bb16b51d593d.png)

2021-11-03 21:25 UTC, brunojuliao commented
> After saving , drawing and then changing background causes this! ![image](https://user-images.githubusercontent.com/29065088/140016986-2f25a974-c5aa-4c53-9105-bb16b51d593d.png)

I need the steps to reproduce. I did save > draw > change bg but on my case it worked. The bg was fully applied. Also, what browser are you using?

2021-11-04 05:53 UTC, yashchaudhari008 commented
### Steps to Reproduce
1. Draw something
2. Click on Save Canvas Button 
3. Now rather than clicking save , click on cancel
4. Change the background color

> Browser:- Chrome Version 95.0.4638.69 (Official Build) (64-bit) \
OS:- Windows 11

2021-11-04 14:42 UTC, brunojuliao commented
A video of me trying to reproduce:
https://youtu.be/RW2ve9mlIyY

2021-11-05 04:46 UTC, yashchaudhari008 commented
I notice that it happens only when it's first run! Check if you can reproduce,

2021-11-06 23:39 UTC, brunojuliao commented
Sorry for the delay. I tried few times. That recording was also a first time run :(

2021-11-07 12:14 UTC, yashchaudhari008 commented
> Sorry for the delay. I tried few times. That recording was also a first time run :(

Hey, i was able to reproduce the bud every time. I will try to test the PR on other OS and browsers , you too try to test on different browser.

2021-11-08 12:47 UTC, yashchaudhari008 commented
Ubuntu Machine:- 
![Screenshot from 2021-11-08 18-12-17](https://user-images.githubusercontent.com/29065088/140744528-9f47e8db-f0c8-4a8d-90af-1ccce84d26db.png)
 I am closing the PR and bug is not been resolved. Thanks for Participating.

2021-11-08 12:47 UTC, closed without merging

2021-11-08 14:04 UTC, yashchaudhari008 commented
Sure, you should have updated the progress 
I could have reopen this PR. Anyways I will check new PR